### ISSUE TITLE
Changes to php7 and pthreads 3.1.6

### ISSUE THREAD

**Issue by ibrunotome** [cfevre/php-ptreads#1]
Hi! I thank you for this repository, but i try to make the changes in .sh to install correctly with php 7.0.9 and pthreads 3.1.6, but the apache doesn't recognise the php installation more... can you help me with that?

**Comment by cfevre** [comment]
Hola Bruno, cree este script como soporte para sistemas antiguos, para las últimas versiones prueba con los tips de instalación que aparecen en http://php.net/manual/en/pthreads.installation.php, saludos.
